# config.py
"""ゲーム全体で使う定数一式。"""

WINNING_ROUNDS = 13
TICK_TIME = 1000

MAX_HP = 100
BODY_DAMAGE = 40
HEADSHOT_DAMAGE = 160
SHOOT_INTERVAL_TICKS = 1

SIDE_PANEL_WIDTH = 260

PLANT_REQUIRED_SECONDS = 4.0
DEFUSE_REQUIRED_SECONDS = 6.0

SMOKE_DURATION_SECONDS = 15.0

MOVING_ACCURACY = 0.50
MOVING_TARGET_HIT_MULTIPLIER = 0.70

BLIND_DURATION_SECONDS = 3.0
FLASH_BURST_DURATION_SECONDS = 2.0
BLIND_ACCURACY_MULTIPLIER = 0.30
FLASH_SPEED_CELLS_PER_TICK = 3
FLASH_MAX_FLIGHT_TICKS = 5

RECON_SPEED_CELLS_PER_TICK = 3
REVEAL_DURATION_SECONDS = 5.0
REVEALED_DODGE_MULTIPLIER = 0.50
RECON_REVEAL_SIZE = 9

COMBO_DISPLAY_TICKS = 3
COMBO_BANNER_HEIGHT = 92