"""プレイヤーコンボ定義。

effect_text は任意です。
省略した場合、bonuses / player_bonuses / renames から自動生成されます。
率系の値は 0.10 = 10ポイントです。
"""

from effect_text_generator import apply_combo_effect_texts

COMBOS = [{'name': '天才と悪魔', 'players': ('jawgemo', 'Demon1'), 'bonuses': {'hs_rate': 0.1}, 'renames': {}},
 {'name': 'ソウルフレンド', 'players': ('F0rsakeN', 'Jinggg'), 'bonuses': {'accuracy': 0.1}, 'renames': {}},
 {'name': '期待の新人', 'players': ('Leo', 'Chronicle'), 'bonuses': {'accuracy': 0.1}, 'renames': {}},
 {'name': '犬猿の仲', 'players': ('Aspas', 'Demon1'), 'bonuses': {'hs_rate': 0.1}, 'renames': {}},
 {'name': '世界一の名門',
  'players': ('Alfajer', 'Boaster', 'Chronicle', 'Derke', 'Leo'),
  'bonuses': {'hs_rate': 0.05, 'accuracy': 0.2},
  'renames': {}},
 {'name': 'ジャパンホープ',
  'players': ('Laz', 'Dep', 'Meiy', 'SugarZ3ro'),
  'bonuses': {'hs_rate': 0.25},
  'renames': {}},
  {'name': 'レイキャビック戦士',
  'players': ('Laz', 'Dep', 'SugarZ3ro'),
  'bonuses': {'hs_rate': 0.1, 'accuracy': 0.1, 'dodge_rate': 0.1},
  'renames': {}},
  {'name': '糖質制限は忍びのたしなみでして',
  'players': ('IbarakiNinja', 'SugarZ3ro'),
  'player_bonuses': {'IbarakiNinja': {'dodge_rate': 0.1, 'accuracy': 0.1, 'reaction': 10}},
  'renames': {}},
  {'name': '偏食家と美食家の違い',
  'players': ('IbarakiNinja', 'Laz'),
  'player_bonuses': {'IbarakiNinja': {'accuracy': 0.1, 'reaction': 10}, 'Laz': {'accuracy': 0.1, 'hs_rate': 0.1}},
  'renames': {}},
 {'name': '天才との別れ', 'players': ('Leo', 'Sayonara'), 'bonuses': {'accuracy': 0.1}, 'renames': {}},
 {'name': '天才と秀才', 'players': ('Leo', 'C0M'), 'bonuses': {'accuracy': 0.1}, 'renames': {}},
 {'name': 'フラッシュバックするトラウマ',
  'players': ('Flashback', 'Demon1', 'Leo'),
  'bonuses': {'accuracy': 0.15},
  'renames': {}},
 {'name': '誰なん君たち', 'players': ('Tortlilyan', 'まーやまくん', 'おもこ'), 'bonuses': {'accuracy': 0.15}, 'renames': {}},
 {'name': '花と剣', 'players': ('Furina', 'Lohen'), 'bonuses': {'reaction': 15}, 'renames': {}},
 {'name': '戦況は傾いている', 'players': ('Furina', 'Kachina'), 'bonuses': {'hs_rate': 0.15}, 'renames': {}},
 {'name': '紫と黄色', 'players': ('Lisa', 'Jean'), 'bonuses': {'hs_rate': 0.15}, 'renames': {}},
 {'name': '寒色の三角関係',
  'players': ('Lisa', 'Lohen', 'Furina'),
  'player_bonuses': {'Lisa': {'dodge_rate': 0.1}, 'Lohen': {'hs_rate': 0.1}, 'Furina': {'accuracy': 0.1}},
  'renames': {}},
 {'name': '同じ青い花を見よう',
  'players': ('Arlecchino', 'Lohen'),
  'bonuses': {'accuracy': 0.1, 'hs_rate': 0.1, 'dodge_rate': -0.05},
  'renames': {}},
 {'name': '生殺与奪の水と炎',
  'players': ('Arlecchino', 'Furina'),
  'bonuses': {'accuracy': 0.2, 'hs_rate': 0.2, 'dodge_rate': -0.1},
  'renames': {}},
 {'name': '圧倒的なスナイパー',
  'players': ('ZMJKK', 'something', 't3xture'),
  'bonuses': {'accuracy': 0.15, 'reaction': 15},
  'renames': {}},
 {'name': '工場現場',
  'players': ('IbarakiNinja', 'Brawk'),
  'bonuses': {'accuracy': 0.2, 'reaction': 5},
  'renames': {}},
 {'name': 'VisionStrikers',
  'players': ('stax', 'Mako', 'Buzz', 'Rb'),
  'bonuses': {'accuracy': 0.2, 'reaction': 10, 'dodge_rate': 0.15},
  'renames': {}},
 {'name': 'スキューバカンカンチュー',
  'players': ('skuba', 'ZMJKK', 'CHICHOO'),
  'bonuses': {'accuracy': 0.2, 'reaction': 10},
  'renames': {}},
 {'name': 'ライチューモッギー',
  'players': ('Lysoar', 'CHICHOO', 'Smoggy'),
  'bonuses': {'accuracy': 0.2, 'reaction': 10},
  'renames': {}},
 {'name': '問題児',
  'players': ('Canezera', 'Rossy', 'Sayonara'),
  'bonuses': {'accuracy': 0.2, 'reaction': 10},
  'renames': {}}]


# 既存の表示処理との互換性を保つため、読み込み時にeffect_textを補完します。
apply_combo_effect_texts(COMBOS)