"""プレイヤーコンボ定義。

effect_text は任意です。
省略した場合、bonuses / player_bonuses / renames から自動生成されます。
率系の値は 0.10 = 10ポイントです。
"""

from effect_text_generator import apply_combo_effect_texts

COMBOS = [{'name': '天才と悪魔', 'players': ('jawgemo', 'Demon1'), 'bonuses': {'hs_rate': 0.1}, 'renames': {}},
 {'name': 'ソウルフレンド', 'players': ('F0rsakeN', 'Jinggg'), 'bonuses': {'accuracy': 0.1}, 'renames': {}},
 {'name': '期待の新人', 'players': ('Leo', 'Chronicle'), 'bonuses': {'accuracy': 0.1}, 'renames': {}},
 {'name': '犬猿の仲', 'players': ('Aspas', 'Demon1'), 'bonuses': {'hs_rate': 0.1}, 'renames': {}},
 {'name': '世界一の名門',
  'players': ('Alfajer', 'Boaster', 'Chronicle', 'Derke', 'Leo'),
  'bonuses': {'hs_rate': 0.1, 'accuracy': 0.4},
  'renames': {}},
 {'name': '悪魔率いる天才集団',
  'players': ('Demon1', 'jawgemo', 'Ethan', 'Boostio', 'C0M'),
  'bonuses': {'reaction': 35, 'accuracy': 0.1},
  'renames': {}},
  {'name': 'ベテランより奇人に',
  'players': ('Ethan', 'Boostio'),
  'player_bonuses': {'Ethan': {'accuracy': 0.1}, 'Boostio': {'iq': 50}},
  'renames': {}},
 {'name': 'ジャパンホープ',
  'players': ('Laz', 'Dep', 'Meiy', 'SugarZ3ro'),
  'bonuses': {'hs_rate': 0.25},
  'renames': {}},
 {'name': 'レイキャビック戦士',
  'players': ('Laz', 'Dep', 'SugarZ3ro'),
  'bonuses': {'hs_rate': 0.1, 'accuracy': 0.1, 'dodge_rate': 0.1},
  'renames': {}},
 {'name': 'クイーンズギャンビット',
  'players': ('nAts', 'Chronicle', 'Lar0k'),
  'bonuses': {'hs_rate': 0.1, 'iq': 30},
  'renames': {}},
 {'name': 'クイーンズフラワー',
  'players': ('leaf', 'Lar0k'),
  'bonuses': {'accuracy': 0.1, 'reaction': 30},
  'renames': {}},
 {'name': 'フラワーギャンビット',
  'players': ('leaf', 'Chronicle', 'nAts'),
  'bonuses': {'accuracy': 0.1, 'iq': 30},
  'renames': {}},
 {'name': 'かつて犠牲になった儚い花',
  'players': ('Lar0k', 'leaf', 'Chronicle', 'nAts', 'Sayonara'),
  'bonuses': {'accuracy': 0.1, 'hs_rate': 0.1, 'iq': 10, 'reaction': 10},
  'renames': {}},
 {'name': '糖質制限は忍びのたしなみでして',
  'players': ('IbarakiNinja', 'SugarZ3ro'),
  'player_bonuses': {'IbarakiNinja': {'dodge_rate': 0.1, 'accuracy': 0.1, 'reaction': 10}},
  'renames': {}},
 {'name': '偏食家と美食家の違い',
  'players': ('IbarakiNinja', 'Laz'),
  'player_bonuses': {'IbarakiNinja': {'accuracy': 0.1, 'reaction': 10}, 'Laz': {'accuracy': 0.1, 'hs_rate': 0.1}},
  'renames': {}},
 {'name': '天才との別れ', 'players': ('Leo', 'Sayonara'), 'bonuses': {'accuracy': 0.1}, 'renames': {}},
 {'name': '天才と秀才', 'players': ('Leo', 'C0M'), 'bonuses': {'accuracy': 0.1}, 'renames': {}},
 {'name': 'フラッシュバックするトラウマ',
  'players': ('Flashback', 'Demon1', 'Leo'),
  'bonuses': {'accuracy': 0.15},
  'renames': {}},
 {'name': '誰なん君たち',
  'players': ('Tortlilyan', 'まーやまくん', 'おもこ'),
  'bonuses': {'accuracy': 0.15},
  'renames': {}},
 {'name': '花と剣', 'players': ('Furina', 'Lohen'), 'player_bonuses': {'Lohen': {'reaction': 15}}, 'renames': {}},
 {'name': '戦況は傾いている',
  'players': ('Furina', 'Kachina'),
  'player_bonuses': {'Kachina': {'hs_rate': 0.15}},
  'renames': {}},
 {'name': '紫と黄色', 'players': ('Lisa', 'Jean'), 'bonuses': {'hs_rate': 0.15}, 'renames': {}},
 {'name': '寒色の三角関係',
  'players': ('Lisa', 'Lohen', 'Furina'),
  'player_bonuses': {'Lisa': {'dodge_rate': 0.1}, 'Lohen': {'hs_rate': 0.1}},
  'renames': {}},
 {'name': '同じ青い花を見よう',
  'players': ('Arlecchino', 'Lohen'),
  'bonuses': {'accuracy': 0.1, 'hs_rate': 0.1, 'dodge_rate': -0.05},
  'renames': {}},
 {'name': '生殺与奪の水と炎',
  'players': ('Arlecchino', 'Furina'),
  'player_bonuses': {'Arlecchino': {'accuracy': 0.2, 'hs_rate': 0.2, 'dodge_rate': -0.1}},
  'renames': {}},
 {'name': '花と鯨',
  'players': ('Furina', 'Tartaglia'),
  'player_bonuses': {'Furina': {'dodge_rate': 0.25, 'iq': 10}},
  'renames': {}},
 {'name': '剣と鯨',
  'players': ('Lohen', 'Tartaglia'),
  'player_bonuses': {'Lohen': {'hs_rate': 0.2, 'reaction': 20}},
  'renames': {}},
 {'name': '圧倒的なスナイパー',
  'players': ('ZMJKK', 'something', 't3xture'),
  'bonuses': {'accuracy': 0.15, 'reaction': 15},
  'renames': {}},
 {'name': '工場現場',
  'players': ('IbarakiNinja', 'Brawk'),
  'bonuses': {'accuracy': 0.2, 'reaction': 5},
  'renames': {}},
 {'name': 'VisionStrikers',
  'players': ('stax', 'Mako', 'Buzz', 'Rb', 'Zest'),
  'bonuses': {'accuracy': 0.3, 'reaction': 65, 'dodge_rate': 0.35, 'iq' : -10},
  'renames': {}},
 {'name': 'スキューバカンカンチュー',
  'players': ('skuba', 'ZMJKK', 'CHICHOO'),
  'bonuses': {'accuracy': 0.2, 'reaction': 10},
  'renames': {}},
 {'name': 'ライチューモッギー',
  'players': ('Lysoar', 'CHICHOO', 'Smoggy'),
  'bonuses': {'accuracy': 0.2, 'reaction': 10},
  'renames': {}},
 {'name': '問題児',
  'players': ('Canezera', 'Rossy', 'Sayonara'),
  'bonuses': {'accuracy': 0.2, 'reaction': 10},
  'renames': {}}]


# 既存の表示処理との互換性を保つため、読み込み時にeffect_textを補完します。
apply_combo_effect_texts(COMBOS)