"""Shared, model-independent contracts for coach_v1."""

from .versions import (
    CHARACTER_ACTION_VERSION,
    CHARACTER_OBSERVATION_VERSION,
    CHECKPOINT_SCHEMA_VERSION,
    COACH_ACTION_VERSION,
    COACH_OBSERVATION_VERSION,
)

__all__ = [
    "CHARACTER_ACTION_VERSION",
    "CHARACTER_OBSERVATION_VERSION",
    "CHECKPOINT_SCHEMA_VERSION",
    "COACH_ACTION_VERSION",
    "COACH_OBSERVATION_VERSION",
]
